version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-myapp}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}

    ports:
      - "${MYSQL_PORT:-3306}:3306"

    volumes:
      - ./storage/mysql/data:/var/lib/mysql
      - ./storage/mysql/logs:/var/log/mysql
      - ./storage/mysql/conf:/etc/mysql/conf.d
      - ./storage/mysql/init:/docker-entrypoint-initdb.d

    networks:
      - devops_net

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  devops_net:
    driver: bridge